###
POST http://0.0.0.0:8080/customer
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@company.com"
}

###
POST http://0.0.0.0:8080/customer
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@company.com"
}

###
POST http://0.0.0.0:8080/customer
Content-Type: application/json

{
  "firstName": "Mary",
  "lastName": "Smith",
  "email": "mary.smith@company.com"
}

###
POST http://0.0.0.0:8080/order
Content-Type: application/json

{
  "number": "1",
  "contents": [
    {
      "item": "Egg",
      "amount": 16,
      "price": 2
    },
    {
      "item": "Bolone",
      "amount": 1,
      "price": 17
    },
    {
      "item": "Chicken",
      "amount": 4,
      "price": 16
    }
  ]
}

###
GET http://0.0.0.0:8080/customer

###
GET http://0.0.0.0:8080/customer/1

###
GET http://0.0.0.0:8080/customer/2

###
GET http://0.0.0.0:8080/customer/5

###
DELETE http://0.0.0.0:8080/customer

###
DELETE http://0.0.0.0:8080/customer/1

###
DELETE http://0.0.0.0:8080/customer/2

###
DELETE http://0.0.0.0:8080/customer/5
